### ISSUE TITLE
Missing form labels 

### ISSUE THREAD

**Issue by nigel-bmlt** [bmlt-enabled/wordpress-bmlt-workflow#19]
Missing form labels

- Online meeting link
- Additional Information
- Both need the for attribute on the label element

@kgrimley-bu

**Comment by nigel-bmlt** [comment]
fixed in 0.3.4

**Comment by klgrimley** [comment]
Ran another check on this one. After looking at the rendered html seeing one interesting quirk and one update that’s needed. 

The quirk is the the `<label for=" virtual_meeting_link">` renders with a space after the opening " so it fails an automated text but shouldn't be an issue with any assistive tech. Therefore a false positive.

The update needed is with the Additional Information. The fieldset doesn't explicitly label the first input. Since it would be goofy to double up the Additional Information text I'd add an id to the fieldset element and then an aria-labeledby attribute to the textarea referencing the id of the fieldset.
